version: v1.0
name: test-issue
jobs:
- job: IssueSync
  steps:
  - github-issue-sync-lark:
      token: '{{.cds.proj.bytest_token}}'
      manager: wangjianliang
      repository: '{{.git.repository}}'
      issue_id: '{{.git.issue.id}}'
      issue_title: '{{.git.issue.title}}'
      issue_action: '{{.git.issue.action}}'
      issue_assignees: '{{.git.issue.assignees}}'
      issue_url: '{{.git.issue.url}}'
      issue_repository: '{{.git.repository}}'
  requirements:
      - plugin: github-issue-sync-lark
      - os-architecture: linux/amd64
      - region: mini
